trigger:
- main  # This triggers the pipeline on pushes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Uses the latest Ubuntu image

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Hello, World!"