trigger:
  branches:
    include:
      - main  # Specify the branch to trigger the pipeline

pool:
  name: Default

steps:

# Step 2: Run Maven build
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-DskipTests=true'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: true
    sonarQubeRunAnalysis: false