trigger:
  branches:
    include:
      - main  # Specify the branch to trigger the pipeline

pool:
  name: Default
  steps:
- task: PowerShell@2
      input
    input:
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Hello, World demo!"
