trigger:
- main 
pool:
  name: 'Default' 

pr:
  branches:
    include:
      - main
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Hello, World demo!"
