trigger:
  branches:
    include:
      - main  # Specify the branch to trigger the pipeline

pool:
  name: Default

stages:
  - stage: 'Junit'
    displayName: 'Junit Stage'
    jobs:
      - job: 'JunitTest'
        displayName: 'Running unit tests'
        steps:
          - script: echo 'Running the spring demo'
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true
          
  