trigger:
  branches:
    include:
      - main  # Adjust this to your desired branch (e.g., 'master', 'develop')

pool:
  name: 'Default'  # Replace this with the name of your self-hosted agent pool

steps:
- task: UseJavaToolInstaller@0
  inputs:
    versionSpec: '11'  # Specify the Java version you want (e.g., '11', '8', '17')
    addToPath: true  # Add Java to PATH so Maven can use it

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your Maven POM file (usually at the root of the project)
    goals: 'clean install'  # Maven goals (clean build)
    options: '-DskipTests=true'  # Skip tests to speed up the build (optional)
  displayName: 'Build with Maven'
